Fix incorrect comparison between double and UINT64_MAX
clang identified a bug here:

```
/__w/tgen/tgen/src/tgen-markovmodel.c:1340:25: error: implicit conversion from 'unsigned long' to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Werror,-Wimplicit-int-float-conversion]
```

This probably didn't matter significantly in practice, since it'd only
make a difference when the generated value rounds to exactly
UINT64_MAX+1.